<?php

namespace AppBundle\Repository;

/**
 * MyentityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyentityRepository extends \Doctrine\ORM\EntityRepository
{
}
