fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


logistique:
    resource: "@LogistiqueBundle/Resources/config/routing.yml"
    prefix:   /logistique

test:
    resource: "@TestBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation




