test:
    resource: "@TestBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

lib_cat:
    resource: "@LibBundle/Controller/CatController.php"
    type:     annotation

lib_livre:
    resource: "@LibBundle/Controller/LivreController.php"
    type:     annotation

lib:
    resource: "@LibBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

mgilet_notification:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications


fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }
