module:
    resource: "@ModuleBundle/Resources/config/routing.yml"
    prefix:   /

logistique:
    resource: "@LogistiqueBundle/Resources/config/routing.yml"
    prefix:   /

lib:
    resource: "@LibBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

classes:
    resource: "@ClassesBundle/Resources/config/routing.yml"
    prefix:   /

branches:
    resource: "@BranchesBundle/Resources/config/routing.yml"
    prefix:   /branche

test:
    resource: "@TestBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix: /app

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
