<?php

namespace LibBundle\Repository;

/**
 * rechRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rechRepository extends \Doctrine\ORM\EntityRepository
{
}
