<?php

namespace LibBundle\Repository;

/**
 * ResRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResRepository extends \Doctrine\ORM\EntityRepository
{
}
