<?php

namespace ModuleBundle\Repository;

/**
 * chapitreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class chapitreRepository extends \Doctrine\ORM\EntityRepository
{
}
