categorie_index:
    path:     /
    defaults: { _controller: "LibBundle:Categorie:index" }
    methods:  GET

categorie_tri:
    path:     /tri
    defaults: { _controller: "LibBundle:Categorie:tri" }

categorie_show:
    path:     /{id}/show
    defaults: { _controller: "LibBundle:Categorie:show" }
    methods:  GET

categorie_liv:
    path:     /{id}/liv
    defaults: { _controller: "LibBundle:Livre:livreparcat" }
    methods:  GET



categorie_new:
    path:     /new
    defaults: { _controller: "LibBundle:Categorie:new" }
    methods:  [GET, POST]

categorie_edit:
    path:     /{id}/edit
    defaults: { _controller: "LibBundle:Categorie:edit" }
    methods:  [GET, POST]

categorie_delete:
    path:     /{id}/delete
    defaults: { _controller: "LibBundle:Categorie:delete" }
    methods:  DELETE
