<?php

namespace LogistiqueBundle\Repository;

/**
 * foyerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class foyerRepository extends \Doctrine\ORM\EntityRepository
{
}
