bus_indexfrontend:
    path:     /busfr
    defaults: { _controller: "LogistiqueBundle:bus:index1" }
    methods:  GET

bus_index:
    path:     /
    defaults: { _controller: "LogistiqueBundle:bus:index" }
    methods:  GET

bus_show:
    path:     /{id}/show
    defaults: { _controller: "LogistiqueBundle:bus:show" }
    methods:  GET

bus_new:
    path:     /new
    defaults: { _controller: "LogistiqueBundle:bus:new" }
    methods:  [GET, POST]

bus_edit:
    path:     /{id}/edit
    defaults: { _controller: "LogistiqueBundle:bus:edit" }
    methods:  [GET, POST]

bus_delete:
    path:     /{id}/delete
    defaults: { _controller: "LogistiqueBundle:bus:delete" }
    methods:  DELETE
